import type { Metadata } from "next";
import "./globals.css";
import "../styles/styles.css";
import ReactQueryProvider from "@/src/providers/ReactQueryProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <div className="w-full md:w-[720px] lg:w-[1140px] mx-auto flex justify-center">
            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default Layout;
