import { UserItem } from "../interfaces/adminUser";

export const userList: UserItem[] = [
  {
    id: 1,
    fullName: "Nguyễn Văn An",
    email: "nguyenvanan@gmail.com",
    phone: "0987 654 321",
    role: "admin",
    status: "Hoạt động",
    createdDate: "01/03/2024",
    createdTime: "10:30",
    enabled: true,
    avatar: "https://i.pravatar.cc/100?img=12",
  },
  {
    id: 2,
    fullName: "Trần Thị Bình",
    email: "tranthibinh@gmail.com",
    phone: "0912 345 678",
    role: "customer",
    status: "Hoạt động",
    createdDate: "28/02/2024",
    createdTime: "14:15",
    enabled: true,
    avatar: "https://i.pravatar.cc/100?img=32",
  },
  {
    id: 3,
    fullName: "Lê Hoàng Nam",
    email: "lehoangnam@gmail.com",
    phone: "0901 234 567",
    role: "customer",
    status: "Đã khóa",
    createdDate: "25/02/2024",
    createdTime: "09:45",
    enabled: false,
    avatar: "https://i.pravatar.cc/100?img=15",
  },
  {
    id: 4,
    fullName: "Phạm Thu Hà",
    email: "phamthuha@gmail.com",
    phone: "0934 567 890",
    role: "admin",
    status: "Hoạt động",
    createdDate: "20/02/2024",
    createdTime: "16:20",
    enabled: true,
    avatar: "https://i.pravatar.cc/100?img=47",
  },
  {
    id: 5,
    fullName: "Đỗ Minh Quân",
    email: "dominhlquan@gmail.com",
    phone: "0978 901 234",
    role: "customer",
    status: "Hoạt động",
    createdDate: "18/02/2024",
    createdTime: "11:05",
    enabled: true,
    avatar: "https://i.pravatar.cc/100?img=68",
  },
];
